### ISSUE TITLE
发这种东西前请先读一读To

### ISSUE THREAD

**Issue by hotstu** [geektheripper/fuck-smartisan#14]
发这种东西前请先读一读ToS
You agree that you will not under any circumstances upload, post, host, or transmit any content that:
**is discriminatory or abusive toward any individual or group;**
While using GitHub, you agree that you will not under any circumstances:
**harass, abuse, threaten, or incite violence towards any individual or group, including GitHub employees, officers, and agents, or other GitHub Users;**

**Comment by geektheripper** [comment]
@hotstu 
感谢提醒，已将项目迁移到私有 Gitlab 仓库：

https://git.dev.geektr.cloud/geektr/fuck-smartisan
https://github.com/geektheripper/fuck-smartisan/blob/rm/readme.md
