### ISSUE TITLE
你应该fuck的是TNT，而不是SOS

### ISSUE THREAD

**Issue by petersunbag** [geektheripper/fuck-smartisan#5]

**Comment by mashirozx** [comment]
不知道TNT的ua长什么样，可以拿来好好定制一下🤔

**Comment by mariotaku** [comment]
@mashirozx **Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15**

**Comment by mashirozx** [comment]
明明就是 Android，写个 Smartisan OS 也算了，UA 竟然还直接写成 Macintosh，锤子这次真的恶心到我了 ![image](https://user-images.githubusercontent.com/16148054/40966898-494aac56-68e4-11e8-9d27-52415d21d77a.png)
![image](https://user-images.githubusercontent.com/16148054/41018380-1737c7f0-698c-11e8-9777-9d2d740f6552.png)
![image](https://user-images.githubusercontent.com/16148054/41018391-24f3e3b0-698c-11e8-82c8-2c3b1a9fa4ec.png)
